### ISSUE TITLE
分身について

### ISSUE THREAD

**Issue by c0a21012** [c0a210401/ProjExD#12]
https://github.com/c0a210401/ProjExD/blob/2897f6d08873e8e4cd88587937354f08f30a8dd1/ex03/maze.py#L42
戻ると本体のこうかとんの場所がわかりずらい

**Comment by c0a210401** [comment]
ご指摘ありがとうございます
分身を残す関数なので修正はしませんが、こういった分かりずらい点をきちんとできるよう、頑張ります
